org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.caching=false
kotlin.incremental=false

systemProp.java.net.useSystemProxies=false
systemProp.http.proxyHost=
systemProp.https.proxyHost=
systemProp.socksProxyHost=
systemProp.socksProxyPort=
