export const DEFAULT_MARKETING_THEME_TOKENS = {
  brandPrimary: "#b8956b",
  brandPrimaryDark: "#9a7a52",
  brandGold: "#c4a052",
  brandSecondary: "#2c2416",
  brandAccent: "#d4a853",
  bgPrimary: "#f5f0e8",
  bgSecondary: "#ede6d6",
  bgCard: "#ffffff",
  bgElevated: "#faf7f2",
  bgDark: "#1a1612",
  textPrimary: "#2c2416",
  textSecondary: "#6b5e4f",
  textMuted: "#9a8b78",
  textInverse: "#faf7f2",
  border: "#ddd4c4",
  borderLight: "#ebe4d8",
};

export const DESIGN_PRESETS = [
  {
    slug: "warm-heritage",
    name: "Warm Heritage",
    description: "Gold and cream palette — current Cullinos marketing look.",
    copyTone: "friendly",
    themeTokens: DEFAULT_MARKETING_THEME_TOKENS,
    layoutHints: { heroLayout: "full-bleed", cardStyle: "soft-shadow", density: "comfortable" },
    imagePrompts: {
      heroRestaurant:
        "Upscale Indian fine-dining restaurant interior at golden hour, warm amber lighting, cinematic wide shot, photorealistic",
      mockupPos:
        "Dark-themed restaurant POS tablet UI, menu grid with Indian dishes, amber accent buttons, charcoal background",
    },
  },
  {
    slug: "dark-charcoal",
    name: "Dark Charcoal",
    description: "Product-led dark theme matching Cullinos portal apps.",
    copyTone: "enterprise",
    themeTokens: {
      brandPrimary: "#d4a017",
      brandPrimaryDark: "#b8860b",
      brandGold: "#d4a017",
      brandSecondary: "#1a1a2e",
      brandAccent: "#f5a623",
      bgPrimary: "#0f0f1a",
      bgSecondary: "#1a1a2e",
      bgCard: "#16213e",
      bgElevated: "#1f2937",
      bgDark: "#0f0f1a",
      textPrimary: "#f9fafb",
      textSecondary: "#9ca3af",
      textMuted: "#6b7280",
      textInverse: "#f9fafb",
      border: "#2a2a3e",
      borderLight: "#3a3a4e",
    },
    layoutHints: { heroLayout: "split", cardStyle: "bordered", density: "compact" },
    imagePrompts: {
      heroRestaurant:
        "Modern restaurant interior dark moody lighting, amber accent lights, wide cinematic, no logos",
      mockupPos: "Dark POS UI mockup with amber highlights, Indian restaurant menu, professional SaaS",
    },
  },
  {
    slug: "clean-minimal",
    name: "Clean Minimal",
    description: "High contrast, minimal shadows, editorial feel.",
    copyTone: "formal",
    themeTokens: {
      brandPrimary: "#1a1612",
      brandPrimaryDark: "#0d0b09",
      brandGold: "#8b7355",
      brandSecondary: "#ffffff",
      brandAccent: "#8b7355",
      bgPrimary: "#ffffff",
      bgSecondary: "#f8f8f8",
      bgCard: "#ffffff",
      bgElevated: "#f3f3f3",
      bgDark: "#1a1612",
      textPrimary: "#111111",
      textSecondary: "#555555",
      textMuted: "#888888",
      textInverse: "#ffffff",
      border: "#e5e5e5",
      borderLight: "#f0f0f0",
    },
    layoutHints: { heroLayout: "split", cardStyle: "flat", density: "spacious" },
    imagePrompts: {
      heroRestaurant: "Minimal white restaurant interior, natural light, editorial photography, clean composition",
      mockupPos: "Minimal light POS UI mockup, black text, subtle borders, professional product screenshot",
    },
  },
] as const;

export const MARKETING_IMAGE_SLOTS = [
  "heroRestaurant",
  "heroKitchen",
  "heroTeam",
  "aboutKitchen",
  "mockupPos",
  "mockupKds",
  "mockupWaiter",
  "mockupOrdering",
  "mockupAdmin",
  "mockupEnterprise",
  "flowCloud",
] as const;

export const SLOT_TO_FILENAME: Record<string, string> = {
  heroRestaurant: "hero-restaurant.png",
  heroKitchen: "hero-kitchen.png",
  heroTeam: "hero-team.png",
  aboutKitchen: "about-kitchen.png",
  mockupPos: "mockup-pos.png",
  mockupKds: "mockup-kds.png",
  mockupWaiter: "mockup-waiter.png",
  mockupOrdering: "mockup-ordering.png",
  mockupAdmin: "mockup-admin.png",
  mockupEnterprise: "mockup-enterprise.png",
  flowCloud: "flow-cloud.png",
};
