import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { CULLINOS_BRAND } from '@/lib/api';
export function AuthLayout({ title, subtitle, children }) {
    return (_jsxs("div", { className: "flex min-h-screen", children: [_jsxs("div", { className: "hidden w-1/2 flex-col justify-between bg-bg-secondary p-12 lg:flex", children: [_jsx("div", { children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "flex h-10 w-10 items-center justify-center rounded-lg bg-brand-primary font-mono text-lg font-bold text-bg-primary", children: "C" }), _jsxs("div", { children: [_jsx("p", { className: "text-xl font-semibold", children: CULLINOS_BRAND.name }), _jsx("p", { className: "text-sm text-text-secondary", children: CULLINOS_BRAND.tagline })] })] }) }), _jsxs("div", { className: "space-y-4", children: [_jsxs("h2", { className: "text-3xl font-semibold leading-tight", children: ["Run your restaurant", _jsx("br", {}), _jsx("span", { className: "text-brand-primary", children: "from one place." })] }), _jsx("p", { className: "max-w-md text-text-secondary", children: "Menu, orders, inventory, staff, and analytics \u2014 unified for modern restaurant operations." })] }), _jsxs("p", { className: "text-sm text-text-muted", children: ["\u00A9 ", new Date().getFullYear(), " ", CULLINOS_BRAND.name] })] }), _jsx("div", { className: "flex w-full flex-col justify-center px-6 py-12 lg:w-1/2 lg:px-16", children: _jsxs("div", { className: "mx-auto w-full max-w-md", children: [_jsx("div", { className: "mb-8 lg:hidden", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "flex h-9 w-9 items-center justify-center rounded-lg bg-brand-primary font-mono font-bold text-bg-primary", children: "C" }), _jsx("span", { className: "text-lg font-semibold", children: CULLINOS_BRAND.name })] }) }), _jsxs("div", { className: "mb-8", children: [_jsx("h1", { className: "text-2xl font-semibold", children: title }), _jsx("p", { className: "mt-2 text-text-secondary", children: subtitle })] }), children] }) })] }));
}
export function AuthFooterLink({ text, linkText, to, }) {
    return (_jsxs("p", { className: "mt-6 text-center text-sm text-text-secondary", children: [text, ' ', _jsx(Link, { to: to, className: "font-medium text-brand-primary hover:text-brand-primary-dark", children: linkText })] }));
}
