apiVersion: v1
kind: ConfigMap
metadata:
  name: cullinos-config
data:
  NODE_ENV: production
  API_URL: https://staging-api.cullinos.com
  GUEST_APP_URL: https://staging-guest.cullinos.com
  ADMIN_APP_URL: https://staging-admin.cullinos.com
  MARKETING_SITE_URL: https://staging.cullinos.com
  CORS_ORIGINS: https://staging-admin.cullinos.com,https://staging-manage.cullinos.com,https://staging-platform.cullinos.com,https://staging-guest.cullinos.com,https://staging-pos.cullinos.com,https://staging-kds.cullinos.com,https://staging.cullinos.com
