apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - namespace.yaml
  - ../../base
  - ingress.yaml

patches:
  - path: config-patch.yaml
  - path: resources-patch.yaml

images:
  - name: ghcr.io/ak2hay/cullinos-api
    newTag: staging
  - name: ghcr.io/ak2hay/cullinos-web
    newTag: staging
  - name: ghcr.io/ak2hay/cullinos-spa-admin
    newTag: staging
  - name: ghcr.io/ak2hay/cullinos-spa-management
    newTag: staging
  - name: ghcr.io/ak2hay/cullinos-spa-super-admin
    newTag: staging
  - name: ghcr.io/ak2hay/cullinos-spa-pos
    newTag: staging
  - name: ghcr.io/ak2hay/cullinos-spa-kds
    newTag: staging
  - name: ghcr.io/ak2hay/cullinos-spa-kiosk
    newTag: staging
  - name: ghcr.io/ak2hay/cullinos-spa-guest-landing
    newTag: staging
  - name: ghcr.io/ak2hay/cullinos-spa-waiter-landing
    newTag: staging
