export const FEATURES = {
  POS: 'pos',
  BILLING: 'billing',
  KOT: 'kot',
  BASIC_REPORTS: 'basic_reports',
  TABLES: 'tables',
  KDS: 'kds',
  INVENTORY: 'inventory',
  RECIPES: 'recipes',
  PURCHASING: 'purchasing',
  CRM: 'crm',
  LOYALTY: 'loyalty',
  QR_ORDERING: 'qr_ordering',
  ONLINE_ORDERING: 'online_ordering',
  DELIVERY: 'delivery',
  MULTI_OUTLET: 'multi_outlet',
  MULTI_BRAND: 'multi_brand',
  FRANCHISE: 'franchise',
  ADVANCED_ANALYTICS: 'advanced_analytics',
  API_ACCESS: 'api_access',
  ROOM_SERVICE: 'room_service',
  ROOM_POSTING: 'room_posting',
  BANQUET: 'banquet',
  HOSPITALITY_INTEGRATIONS: 'hospitality_integrations',
  COUNTER_MODE: 'counter_mode',
  PICKUP_QUEUE: 'pickup_queue',
  PRE_ORDERS: 'pre_orders',
  PRODUCTION: 'production',
  EVENTS: 'events',
} as const;

export type FeatureKey = (typeof FEATURES)[keyof typeof FEATURES];

/**
 * Maps product FeatureKeys to DB SubscriptionEntitlement module keys.
 * Features without a module are behavior flags (operatingMode / public routes).
 */
export const FEATURE_TO_MODULE: Partial<Record<FeatureKey, string>> = {
  [FEATURES.POS]: 'pos',
  [FEATURES.BILLING]: 'billing',
  [FEATURES.KOT]: 'orders',
  [FEATURES.BASIC_REPORTS]: 'reports',
  [FEATURES.TABLES]: 'tables',
  [FEATURES.KDS]: 'kds',
  [FEATURES.INVENTORY]: 'inventory',
  [FEATURES.RECIPES]: 'inventory',
  [FEATURES.PURCHASING]: 'inventory',
  [FEATURES.CRM]: 'crm',
  [FEATURES.LOYALTY]: 'loyalty',
  [FEATURES.QR_ORDERING]: 'customer',
  [FEATURES.ONLINE_ORDERING]: 'customer',
  [FEATURES.DELIVERY]: 'delivery',
  [FEATURES.MULTI_OUTLET]: 'management',
  [FEATURES.MULTI_BRAND]: 'management',
  [FEATURES.FRANCHISE]: 'franchise',
  [FEATURES.ADVANCED_ANALYTICS]: 'analytics',
  [FEATURES.API_ACCESS]: 'management',
  [FEATURES.ROOM_SERVICE]: 'hotel',
  [FEATURES.ROOM_POSTING]: 'hotel',
  [FEATURES.BANQUET]: 'hotel',
  [FEATURES.HOSPITALITY_INTEGRATIONS]: 'hotel',
  [FEATURES.PICKUP_QUEUE]: 'kds',
  [FEATURES.PRODUCTION]: 'production',
  [FEATURES.EVENTS]: 'events',
  [FEATURES.PRE_ORDERS]: 'orders',
  [FEATURES.COUNTER_MODE]: 'pos',
};

/** Canonical subscription entitlement module keys for plan editors. */
export const PLAN_MODULES = [
  'pos',
  'kds',
  'admin',
  'waiter',
  'customer',
  'menu',
  'orders',
  'tables',
  'billing',
  'tax',
  'inventory',
  'crm',
  'loyalty',
  'management',
  'franchise',
  'hotel',
  'analytics',
  'delivery',
  'settings',
  'reports',
  'events',
  'production',
] as const;

export type PlanModule = (typeof PLAN_MODULES)[number];

export const PLAN_FEATURES: Record<string, FeatureKey[]> = {
  STARTER: [
    FEATURES.POS,
    FEATURES.BILLING,
    FEATURES.KOT,
    FEATURES.BASIC_REPORTS,
    FEATURES.TABLES,
    FEATURES.KDS,
    FEATURES.QR_ORDERING,
    FEATURES.ONLINE_ORDERING,
  ],
  QSR: [
    FEATURES.POS,
    FEATURES.BILLING,
    FEATURES.KOT,
    FEATURES.BASIC_REPORTS,
    FEATURES.COUNTER_MODE,
    FEATURES.PICKUP_QUEUE,
    FEATURES.KDS,
    FEATURES.TABLES,
    FEATURES.QR_ORDERING,
    FEATURES.ONLINE_ORDERING,
    FEATURES.LOYALTY,
    FEATURES.INVENTORY,
    FEATURES.RECIPES,
    FEATURES.EVENTS,
    FEATURES.PRODUCTION,
  ],
  PROFESSIONAL: [
    FEATURES.POS,
    FEATURES.BILLING,
    FEATURES.KOT,
    FEATURES.BASIC_REPORTS,
    FEATURES.TABLES,
    FEATURES.KDS,
    FEATURES.INVENTORY,
    FEATURES.RECIPES,
    FEATURES.PURCHASING,
    FEATURES.CRM,
    FEATURES.LOYALTY,
    FEATURES.QR_ORDERING,
    FEATURES.ONLINE_ORDERING,
    FEATURES.DELIVERY,
    FEATURES.PICKUP_QUEUE,
    FEATURES.PRODUCTION,
    FEATURES.EVENTS,
  ],
  ENTERPRISE: [
    FEATURES.POS,
    FEATURES.BILLING,
    FEATURES.KOT,
    FEATURES.BASIC_REPORTS,
    FEATURES.TABLES,
    FEATURES.KDS,
    FEATURES.INVENTORY,
    FEATURES.RECIPES,
    FEATURES.PURCHASING,
    FEATURES.CRM,
    FEATURES.LOYALTY,
    FEATURES.QR_ORDERING,
    FEATURES.ONLINE_ORDERING,
    FEATURES.DELIVERY,
    FEATURES.MULTI_OUTLET,
    FEATURES.MULTI_BRAND,
    FEATURES.FRANCHISE,
    FEATURES.ADVANCED_ANALYTICS,
    FEATURES.API_ACCESS,
    FEATURES.PICKUP_QUEUE,
    FEATURES.PRODUCTION,
    FEATURES.EVENTS,
  ],
  HOSPITALITY: [
    FEATURES.POS,
    FEATURES.BILLING,
    FEATURES.KOT,
    FEATURES.BASIC_REPORTS,
    FEATURES.TABLES,
    FEATURES.KDS,
    FEATURES.INVENTORY,
    FEATURES.RECIPES,
    FEATURES.PURCHASING,
    FEATURES.CRM,
    FEATURES.LOYALTY,
    FEATURES.QR_ORDERING,
    FEATURES.ONLINE_ORDERING,
    FEATURES.DELIVERY,
    FEATURES.MULTI_OUTLET,
    FEATURES.MULTI_BRAND,
    FEATURES.FRANCHISE,
    FEATURES.ADVANCED_ANALYTICS,
    FEATURES.API_ACCESS,
    FEATURES.ROOM_SERVICE,
    FEATURES.ROOM_POSTING,
    FEATURES.BANQUET,
    FEATURES.HOSPITALITY_INTEGRATIONS,
  ],
};
