export const PERMISSIONS = {
  // Organizations
  ORG_READ: 'org:read',
  ORG_UPDATE: 'org:update',
  ORG_MANAGE_USERS: 'org:manage_users',
  ORG_MANAGE_SETTINGS: 'org:manage_settings',

  // Outlets
  OUTLET_READ: 'outlet:read',
  OUTLET_CREATE: 'outlet:create',
  OUTLET_UPDATE: 'outlet:update',
  OUTLET_DELETE: 'outlet:delete',

  // Menu
  MENU_READ: 'menu:read',
  MENU_CREATE: 'menu:create',
  MENU_UPDATE: 'menu:update',
  MENU_DELETE: 'menu:delete',

  // Orders
  ORDER_READ: 'order:read',
  ORDER_CREATE: 'order:create',
  ORDER_UPDATE: 'order:update',
  ORDER_CANCEL: 'order:cancel',
  ORDER_DISCOUNT: 'order:discount',
  ORDER_DISCOUNT_APPROVE: 'order:discount:approve',
  ORDER_PRICE_OVERRIDE: 'order:price_override',
  ORDER_REFUND: 'order:refund',

  // POS
  POS_ACCESS: 'pos:access',
  POS_SHIFT_OPEN: 'pos:shift:open',
  POS_SHIFT_CLOSE: 'pos:shift:close',
  POS_DAY_CLOSE: 'pos:day:close',

  // Kitchen
  KITCHEN_READ: 'kitchen:read',
  KITCHEN_UPDATE: 'kitchen:update',

  // Tables
  TABLE_READ: 'table:read',
  TABLE_MANAGE: 'table:manage',

  // Inventory
  INVENTORY_READ: 'inventory:read',
  INVENTORY_ADJUST: 'inventory:adjust',
  INVENTORY_TRANSFER: 'inventory:transfer',

  // Purchasing
  PURCHASE_READ: 'purchase:read',
  PURCHASE_CREATE: 'purchase:create',
  PURCHASE_APPROVE: 'purchase:approve',

  // Customers
  CUSTOMER_READ: 'customer:read',
  CUSTOMER_CREATE: 'customer:create',
  CUSTOMER_UPDATE: 'customer:update',

  // Reports
  REPORTS_READ: 'reports:read',
  REPORTS_EXPORT: 'reports:export',

  // Staff
  STAFF_READ: 'staff:read',
  STAFF_MANAGE: 'staff:manage',

  // Settings
  SETTINGS_READ: 'settings:read',
  SETTINGS_UPDATE: 'settings:update',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const DEFAULT_ROLE_PERMISSIONS: Record<string, Permission[]> = {
  OWNER: Object.values(PERMISSIONS),
  ADMIN: Object.values(PERMISSIONS),
  MANAGER: [
    PERMISSIONS.ORG_READ,
    PERMISSIONS.OUTLET_READ,
    PERMISSIONS.MENU_READ,
    PERMISSIONS.MENU_CREATE,
    PERMISSIONS.MENU_UPDATE,
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.ORDER_CANCEL,
    PERMISSIONS.ORDER_DISCOUNT,
    PERMISSIONS.ORDER_DISCOUNT_APPROVE,
    PERMISSIONS.POS_ACCESS,
    PERMISSIONS.POS_SHIFT_OPEN,
    PERMISSIONS.POS_SHIFT_CLOSE,
    PERMISSIONS.KITCHEN_READ,
    PERMISSIONS.KITCHEN_UPDATE,
    PERMISSIONS.TABLE_READ,
    PERMISSIONS.TABLE_MANAGE,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.PURCHASE_READ,
    PERMISSIONS.PURCHASE_CREATE,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.STAFF_READ,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_UPDATE,
  ],
  CASHIER: [
    PERMISSIONS.OUTLET_READ,
    PERMISSIONS.MENU_READ,
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.ORDER_DISCOUNT,
    PERMISSIONS.POS_ACCESS,
    PERMISSIONS.POS_SHIFT_OPEN,
    PERMISSIONS.POS_SHIFT_CLOSE,
    PERMISSIONS.TABLE_READ,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
  ],
  WAITER: [
    PERMISSIONS.MENU_READ,
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.TABLE_READ,
    PERMISSIONS.TABLE_MANAGE,
    PERMISSIONS.CUSTOMER_READ,
  ],
  KITCHEN_MANAGER: [
    PERMISSIONS.MENU_READ,
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.KITCHEN_READ,
    PERMISSIONS.KITCHEN_UPDATE,
    PERMISSIONS.INVENTORY_READ,
  ],
  CHEF: [
    PERMISSIONS.MENU_READ,
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.KITCHEN_READ,
    PERMISSIONS.KITCHEN_UPDATE,
  ],
  INVENTORY_MANAGER: [
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.PURCHASE_READ,
    PERMISSIONS.PURCHASE_CREATE,
    PERMISSIONS.REPORTS_READ,
  ],
  ACCOUNTANT: [
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.PURCHASE_READ,
    PERMISSIONS.ORDER_READ,
  ],
};
