import {
  Armchair,
  BedDouble,
  Bike,
  BookOpen,
  Calculator,
  CalendarCheck,
  CalendarDays,
  ChartColumn,
  ChefHat,
  ClipboardList,
  CreditCard,
  Factory,
  Image,
  LayoutDashboard,
  MessageSquare,
  MonitorPlay,
  Package,
  PartyPopper,
  Plug,
  Rocket,
  Settings,
  ShoppingCart,
  Star,
  Store,
  TabletSmartphone,
  Tags,
  TicketPercent,
  Truck,
  UserCog,
  UserRound,
  Users,
  UtensilsCrossed,
  Warehouse,
  Circle,
  type LucideIcon,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  orders: ClipboardList,
  pos: Calculator,
  tables: Armchair,
  reservations: CalendarCheck,
  displays: MonitorPlay,
  stations: ChefHat,
  kiosk: TabletSmartphone,
  delivery: Bike,
  aggregators: Plug,
  menu: UtensilsCrossed,
  inventory: Package,
  recipes: BookOpen,
  purchasing: ShoppingCart,
  suppliers: Truck,
  production: Factory,
  centralKitchen: Warehouse,
  brands: Tags,
  customers: Users,
  loyalty: Star,
  guests: UserRound,
  rooms: BedDouble,
  events: CalendarDays,
  banquets: PartyPopper,
  marketplace: Store,
  coupons: TicketPercent,
  banners: Image,
  sms: MessageSquare,
  staff: UserCog,
  reports: ChartColumn,
  onboarding: Rocket,
  settings: Settings,
  billing: CreditCard,
  default: Circle,
};

export function NavIcon({ name, size = 18 }: { name: string; size?: number }) {
  const Icon = ICONS[name] ?? Circle;
  return <Icon size={size} strokeWidth={1.9} aria-hidden="true" />;
}

const PREFIXES: Array<[string, string]> = [
  ['/orders', 'orders'],
  ['/pos', 'pos'],
  ['/tables', 'tables'],
  ['/reservations', 'reservations'],
  ['/displays', 'displays'],
  ['/promo-display', 'displays'],
  ['/cds', 'displays'],
  ['/kds', 'displays'],
  ['/stations', 'stations'],
  ['/kiosk', 'kiosk'],
  ['/delivery', 'delivery'],
  ['/aggregators', 'aggregators'],
  ['/menu', 'menu'],
  ['/inventory', 'inventory'],
  ['/recipes', 'recipes'],
  ['/purchasing', 'purchasing'],
  ['/suppliers', 'suppliers'],
  ['/production', 'production'],
  ['/central-kitchen', 'centralKitchen'],
  ['/brands', 'brands'],
  ['/customers', 'customers'],
  ['/loyalty', 'loyalty'],
  ['/hospitality/guests', 'guests'],
  ['/hospitality/rooms', 'rooms'],
  ['/events', 'events'],
  ['/banquets', 'banquets'],
  ['/marketplace', 'marketplace'],
  ['/coupons', 'coupons'],
  ['/guest-banners', 'banners'],
  ['/sms', 'sms'],
  ['/staff', 'staff'],
  ['/reports', 'reports'],
  ['/onboarding', 'onboarding'],
  ['/settings', 'settings'],
  ['/payments', 'settings'],
  ['/billing', 'billing'],
];

export function iconForPath(path: string): string {
  if (path === '/') return 'dashboard';
  return PREFIXES.find(([prefix]) => path.startsWith(prefix))?.[1] ?? 'default';
}
