import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useQuery } from '@tanstack/react-query';
import { franchiseApi } from '@/lib/api';
export function FranchisePage() {
    const { data: franchisees = [], isLoading, error } = useQuery({
        queryKey: ['franchise', 'franchisees'],
        queryFn: franchiseApi.listFranchisees,
        retry: false,
    });
    const activeCount = franchisees.filter((f) => f.status === 'ACTIVE').length;
    return (_jsxs("div", { className: "space-y-8", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-semibold", children: "Franchise overview" }), _jsx("p", { className: "mt-1 text-text-secondary", children: "Monitor franchisees, agreements, and outlet coverage across your brand." })] }), _jsxs("div", { className: "grid gap-4 sm:grid-cols-3", children: [_jsxs("div", { className: "rounded-xl border border-white/5 bg-bg-card p-5", children: [_jsx("p", { className: "text-sm text-text-muted", children: "Total franchisees" }), _jsx("p", { className: "mt-2 text-2xl font-semibold", children: isLoading ? '…' : franchisees.length })] }), _jsxs("div", { className: "rounded-xl border border-white/5 bg-bg-card p-5", children: [_jsx("p", { className: "text-sm text-text-muted", children: "Active" }), _jsx("p", { className: "mt-2 text-2xl font-semibold text-status-success", children: isLoading ? '…' : activeCount })] }), _jsxs("div", { className: "rounded-xl border border-white/5 bg-bg-card p-5", children: [_jsx("p", { className: "text-sm text-text-muted", children: "Total outlets" }), _jsx("p", { className: "mt-2 text-2xl font-semibold", children: isLoading ? '…' : franchisees.reduce((sum, f) => sum + f.outletCount, 0) })] })] }), error ? (_jsx("div", { className: "rounded-xl border border-status-warning/30 bg-status-warning/10 px-4 py-3 text-sm text-status-warning", children: "Franchise API unavailable \u2014 data will appear when endpoints are connected." })) : null, _jsxs("section", { className: "rounded-xl border border-white/5 bg-bg-card p-6", children: [_jsx("h2", { className: "font-medium", children: "Franchisees" }), _jsx("div", { className: "mt-4 overflow-x-auto", children: _jsxs("table", { className: "w-full text-left text-sm", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b border-white/5 text-text-muted", children: [_jsx("th", { className: "pb-3 pr-4 font-medium", children: "Name" }), _jsx("th", { className: "pb-3 pr-4 font-medium", children: "Contact" }), _jsx("th", { className: "pb-3 pr-4 font-medium", children: "Status" }), _jsx("th", { className: "pb-3 pr-4 font-medium", children: "Outlets" }), _jsx("th", { className: "pb-3 font-medium", children: "Agreements" })] }) }), _jsxs("tbody", { children: [franchisees.map((f) => (_jsxs("tr", { className: "border-b border-white/5", children: [_jsx("td", { className: "py-3 pr-4 font-medium", children: f.name }), _jsx("td", { className: "py-3 pr-4 text-text-secondary", children: f.contactEmail ?? f.contactPhone ?? '—' }), _jsx("td", { className: "py-3 pr-4", children: _jsx("span", { className: `rounded-full px-2 py-0.5 text-xs ${f.status === 'ACTIVE'
                                                            ? 'bg-status-success/15 text-status-success'
                                                            : 'bg-status-warning/15 text-status-warning'}`, children: f.status }) }), _jsx("td", { className: "py-3 pr-4", children: f.outletCount }), _jsx("td", { className: "py-3", children: f.agreementCount })] }, f.id))), !isLoading && franchisees.length === 0 ? (_jsx("tr", { children: _jsx("td", { colSpan: 5, className: "py-6 text-center text-text-muted", children: "No franchisees registered yet" }) })) : null] })] }) })] })] }));
}
